# Server
server.port=8080

# H2 (para desarrollo local sin PostgreSQL)
spring.datasource.url=jdbc:h2:mem:pokemon_tcg
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Pokémon TCG API
pokemon.api.key=eaa3e51f-95b3-4b82-85b0-49911dcb4a7e
pokemon.api.base-url=https://api.pokemontcg.io/v2

# CORS
app.cors.allowed-origins=http://localhost:4200