# Server
server.port=8080

# Database
spring.datasource.url=jdbc:h2:file:./.data/pokemon_tcg_dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.default-property-inclusion=non_null

# Pokemon TCG API
pokemon.api.key=${POKEMON_API_KEY:eaa3e51f-95b3-4b82-85b0-49911dcb4a7e}
pokemon.api.base-url=${POKEMON_API_BASE_URL:https://api.pokemontcg.io/v2}

# CORS
app.cors.allowed-origins=http://localhost:4200
