CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_valid BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_decks_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

CREATE TABLE cards_in_deck (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL,
    card_id VARCHAR(50) NOT NULL,
    quantity INT NOT NULL,
    CONSTRAINT fk_cards_in_deck_deck FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE,
    CONSTRAINT uq_cards_in_deck UNIQUE (deck_id, card_id)
);

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player1_id BIGINT NOT NULL,
    player2_id BIGINT,
    player1_deck_id BIGINT NOT NULL,
    player2_deck_id BIGINT,
    status VARCHAR(20) DEFAULT 'WAITING',
    current_turn_player_id BIGINT,
    turn_number INT DEFAULT 0,
    is_first_turn BOOLEAN DEFAULT TRUE,
    winner_id BIGINT,
    victory_condition VARCHAR(30),
    is_sudden_death BOOLEAN DEFAULT FALSE,
    parent_game_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    CONSTRAINT fk_games_player1 FOREIGN KEY (player1_id) REFERENCES players(id),
    CONSTRAINT fk_games_player2 FOREIGN KEY (player2_id) REFERENCES players(id),
    CONSTRAINT fk_games_player1_deck FOREIGN KEY (player1_deck_id) REFERENCES decks(id),
    CONSTRAINT fk_games_player2_deck FOREIGN KEY (player2_deck_id) REFERENCES decks(id),
    CONSTRAINT fk_games_winner FOREIGN KEY (winner_id) REFERENCES players(id)
);

CREATE TABLE game_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT UNIQUE NOT NULL,
    p1_deck VARCHAR,
    p1_hand VARCHAR,
    p1_prizes VARCHAR,
    p1_discard VARCHAR,
    p1_active_pokemon VARCHAR,
    p1_bench VARCHAR,
    p2_deck VARCHAR,
    p2_hand VARCHAR,
    p2_prizes VARCHAR,
    p2_discard VARCHAR,
    p2_active_pokemon VARCHAR,
    p2_bench VARCHAR,
    stadium_card VARCHAR,
    pending_bench_damage VARCHAR,
    energy_attached_this_turn BOOLEAN DEFAULT FALSE,
    supporter_played_this_turn BOOLEAN DEFAULT FALSE,
    stadium_played_this_turn BOOLEAN DEFAULT FALSE,
    retreat_used_this_turn BOOLEAN DEFAULT FALSE,
    p1_ready_to_start BOOLEAN DEFAULT FALSE,
    p2_ready_to_start BOOLEAN DEFAULT FALSE,
    p1_mulligan_count INT DEFAULT 0,
    p2_mulligan_count INT DEFAULT 0,
    p1_can_draw_extra BOOLEAN DEFAULT FALSE,
    p2_can_draw_extra BOOLEAN DEFAULT FALSE,
    setup_step VARCHAR(40) DEFAULT 'MULLIGAN_CHECK',
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_game_states_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

CREATE TABLE turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    turn_number INT NOT NULL,
    player_id BIGINT NOT NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP,
    CONSTRAINT fk_turns_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    CONSTRAINT fk_turns_player FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id BIGINT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    action_data VARCHAR NOT NULL DEFAULT '{}',
    is_valid BOOLEAN DEFAULT TRUE,
    validation_error VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_actions_turn FOREIGN KEY (turn_id) REFERENCES turns(id) ON DELETE CASCADE
);
