package com.pokemon.tcg.engine.model;

public enum GameEventType {
    CARD_DRAWN, POKEMON_PLACED, ENERGY_ATTACHED, TRAINER_PLAYED,
    POKEMON_EVOLVED, POKEMON_RETREATED, ATTACK_EXECUTED,
    DAMAGE_DEALT, POKEMON_KNOCKED_OUT, PRIZE_TAKEN,
    STATUS_APPLIED, STATUS_CURED, TURN_ENDED, GAME_OVER,
    COIN_FLIP, MULLIGAN_PLAYER, MULLIGAN_BOTH, MULLIGAN_NEEDED,
    CHOOSE_REPLACEMENT,
    SETUP_ACTION, GAME_READY,
    BENCH_DAMAGE_PENDING, POKEMON_HEALED
}
